# Generated by Django 4.1.7 on 2023-03-30 18:15

import app_authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_authentication",
            "0002_alter_users_options_alter_users_managers_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[
                ("objects", app_authentication.models.UsersManager()),
            ],
        ),
    ]
