# Generated by Django 4.1.7 on 2023-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_authentication", "0003_contributor_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="permission",
            field=models.CharField(
                choices=[("R", "Responsable"), ("C", "Contributeur")],
                default="C",
                max_length=1,
            ),
        ),
    ]
