# Generated by Django 4.1.7 on 2023-03-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_softdesk", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
    ]
