# Generated by Django 4.1.7 on 2023-04-02 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app_softdesk", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
